name: Build Release

on:
  push:
    tags:
      - '*'
      
jobs:
  build-release:
    name: Build and Upload a release
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source
        uses: actions/checkout@v2

      - name: Create ENV
        id: create-env
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2-)" >> "$GITHUB_OUTPUT"
          echo "VER=$(echo $GITHUB_REF | cut -d '/' -f 3-)" >> "$GITHUB_OUTPUT"

      - name: NPM Install
        run: |
          npm install
          
      - name: Build
        run: |
          npm run cordova build -- --release --device

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create-env.outputs.VER }}
          release_name: Release ${{ steps.create-env.outputs.VER }}
          draft: false
          prerelease: false
          
      - name: Upload release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./platforms/android/app/build/outputs/bundle/release/app-release.aab
          asset_name: ${{ steps.create-env.outputs.REPO }}-${{ steps.create-env.outputs.VER }}.aab
          asset_content_type: application/java-archive
